echocatcher:
  #list of publisher to listen to. (they should return the echo)
  publishers:
      - "tcp://zmq.testnet.iota.org:5556"

      - "tcp://m5.iotaledger.net:5556"
  #url of iri node
  iri_host: "https://nodes.testnet.iota.org:443"
  #IP/Port that the Prometheus Exposer binds to
  prometheus_exposer_uri: "0.0.0.0:8080"
  #MWM for transaction's POW
  mwm: 9
  #time for db to load from publishers zmq [seconds]
  tangledb_warmup_period: 360
  #in-between transactions interval [seconds]
  broadcast_interval: 20

statscollector:

  #IP/Port that the Prometheus Exposer binds to
  prometheus_exposer_uri: "0.0.0.0:8081"
  #URL of ZMQ publisher to connect to
  publishers:
      - "tcp://zmq.testnet.iota.org:5556"

      - "tcp://m5.iotaledger.net:5556"
  #interval to wait before starting publishing in milliseconds
  pub_delay: 120000
  #interval on which to publish to prometheus in milliseconds. You probably don't want to change this.
  pub_interval: 1000
